### ISSUE TITLE
can't work on win10

### ISSUE THREAD

**Issue by purequant** [Monacraft/AnkiDiscord#6] opened 2019-06-06 11:18 UTC
错误
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的忽略掉你已经安装的插件。
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。
当你已经发现是因为插件引起的问题，请在我们的支持网站上 add-ons section 上报告问题。
调试信息
Anki 2.1.13 (3ba55990) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=?

failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-0'
failed to open '\\\\?\\pipe\\discord-ipc-1': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-1'
failed to open '\\\\?\\pipe\\discord-ipc-2': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-2'
failed to open '\\\\?\\pipe\\discord-ipc-3': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-3'
failed to open '\\\\?\\pipe\\discord-ipc-4': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-4'
failed to open '\\\\?\\pipe\\discord-ipc-5': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-5'
failed to open '\\\\?\\pipe\\discord-ipc-6': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-6'
failed to open '\\\\?\\pipe\\discord-ipc-7': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-7'
failed to open '\\\\?\\pipe\\discord-ipc-8': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-8'
failed to open '\\\\?\\pipe\\discord-ipc-9': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-9'

**Comment by mjuzikfrik** [comment] 2019-06-24 14:57
I've got the same problem. Could it be due to Windows not being in English?
Anki 2.1.14 (702788c8) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=?

failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-0'
failed to open '\\\\?\\pipe\\discord-ipc-1': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-1'
failed to open '\\\\?\\pipe\\discord-ipc-2': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-2'
failed to open '\\\\?\\pipe\\discord-ipc-3': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-3'
failed to open '\\\\?\\pipe\\discord-ipc-4': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-4'
failed to open '\\\\?\\pipe\\discord-ipc-5': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-5'
failed to open '\\\\?\\pipe\\discord-ipc-6': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-6'
failed to open '\\\\?\\pipe\\discord-ipc-7': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-7'
failed to open '\\\\?\\pipe\\discord-ipc-8': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-8'
failed to open '\\\\?\\pipe\\discord-ipc-9': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-9'

**Comment by mjuzikfrik** [comment] 2019-06-25 17:49
Version downloaded through anki addon page doesn't work giving me the above mentioned error but the version from github works without any problems. :)

**Comment by Monacraft** [comment] 2020-01-05 12:22
This is an issue associated with discord not being open when you load Anki (the RPC expects discord to be running).

I've fixed the issue and thought I added it to Anki Web. I'll double check and upload the new code soon.

**Comment by Monacraft** [comment] 2020-01-05 12:25
Duplicate of #1

**Closed by Monacraft** 2020-01-05 12:25 UTC
